---
# to generate markers you can e.g. go here: https://chev.me/arucogen/

# marker_config:
#   dictionary: 'DICT_6X6_250'
#   marker_length: 0.2

board_config:
  - type: 'grid'
    dictionary: 'DICT_5X5_50'
    x: 2
    y: 2
    marker_length: 0.035
    separation: 0.0015
    first_marker: 32
  - type: 'grid'
    dictionary: 'DICT_5X5_50'
    x: 2
    y: 2
    marker_length: 0.035
    separation: 0.0015
    first_marker: 36
  - type: 'grid'
    dictionary: 'DICT_5X5_50'
    x: 2
    y: 2
    marker_length: 0.035
    separation: 0.0015
    first_marker: 40

average_estimations: True
max_analyzer_list: 10
max_detection_age: 1
max_detection_images: 10

number_of_workers: 1

print_in_image: True
draw_detected_markers: True
draw_axis: True

cameras:
  - camera_front:
      frame_id: gazebo_camera3d_front
  - camera_rear:
      frame_id: gazebo_camera3d_rear
