#!/usr/bin/env python

import rospy
from aruco_analyzer.ros_wrapper import ARMarkerDetectorWrapper
from aruco_analyzer.ros_wrapper.route_logger_to_ros import route_logger_to_ros

if __name__ == '__main__':
    rospy.init_node('ARMarkerDetectorWrapper', log_level=rospy.ERROR)
    route_logger_to_ros('aruco_analyzer')
    ar_detector = ARMarkerDetectorWrapper()
    start_time = rospy.Time.now().secs
    while not rospy.is_shutdown():
        time_s = rospy.Time.now().secs - start_time
        # rospy.loginfo("{} is running since: {}".format(ar_detector.name, time.strftime('%H:%M:%S', time.gmtime(time_s))))
        rospy.sleep(1)
